name: Build Kivy APK Stable

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          git zip unzip wget \
          openjdk-17-jdk \
          build-essential \
          python3-pip \
          libffi-dev libssl-dev

    - name: Install Buildozer stable stack
      run: |
        pip install --upgrade pip
        pip install cython==0.29.36
        pip install kivy==2.2.1
        pip install buildozer==1.5.0
        pip install python-for-android==2023.9.16

    - name: Clean
      run: |
        rm -rf .buildozer

    - name: Build APK
      run: |
        export CI=1
        export DEBIAN_FRONTEND=noninteractive

        yes | buildozer android debug
